### ISSUE TITLE
JSDoc redefines Amount, Brand, ...

### ISSUE THREAD

**Issue by dckc** [Agoric/ui-kit#103]
## Describe the bug

generated docs show `Amount`, `Brand` and such as if defined in the web-components package.

## To Reproduce
1. `yarn; yarn docs`
2. open `api-docs/index.html`
3. open **web-components**
4. See `Amount`, `Brand`, ...

## Expected behavior

ideally, those types should link to the respective types in https://agoric-sdk.pages.dev/modules/_agoric_ertp ... but... hm... those seem to be missing :-/

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Additional context

https://github.com/Agoric/ui-kit/blob/216cc5b36e624d61740a72cbea1c41e9039eed51/packages/web-components/src/display/display.js#L10-L13

The new `@import` stuff would probably help.

## Screenshots

![image](https://github.com/Agoric/ui-kit/assets/150986/e8a3e4a9-27af-472e-9447-45e167f7c90e)

cc @turadg @samsiegart

**Comment by turadg** [comment]
@samsiegart I tried TS 5.5 (nightly) and it hit some error parsing a cosmjs file. Same error in 5.4. 

I think a higher value approach would be to move to `.ts` syntax here
