### ISSUE TITLE
chainStorageWatcher throws on no smart-wallet provisioned

### ISSUE THREAD

**Issue by WietzeSlagman** [Agoric/ui-kit#50]
## Describe the bug
No smart-wallet error makes it so chainStorageWatcher throws, this prevents the ability to use the chainStorageWatcher functionality atall, including `provisionSmartWallet()`

## Expected behavior
chainStorageWatcher not to throw on no smart-wallet provisioned

**Comment by samsiegart** [comment]
This is fixed in the latest release of `@agoric/web-components`
