### ISSUE TITLE
Audit chain queries

### ISSUE THREAD

**Issue by samsiegart** [Agoric/ui-kit#53]
## What is the Problem Being Solved?

There are multiple ways to query on-chain data between rpc, grpc, json api etc. We should make sure that the dapps (and keplr) are querying the agoric chain in a future-proof way that will not break for any impending chain software upgrades. If the query implementation needs to change, we need to identify a future-proof way to do the same queries while staying under 2qps for current dapps and limiting bandwidth consumption.

## Description of the Design

Schedule a meeting between @samsiegart , @gibson042 , and @michaelfig to audit the dapp/keplr queries as described above. This issue can be resolved as long as the above questions are answered and documented somewhere. Any future work will be planned in separate issues.

**Comment by samsiegart** [comment]
Meeting Notes:

- Keplr queries i.e. https://github.com/chainapsis/keplr-wallet/blob/master/packages/stores/src/query/agoric/vbank-assets.ts are future-proof, require a `toml` config to enable in nodes, we should ensure we're communicating that with our node providers.
- Dapp batch queries i.e. https://github.com/Agoric/ui-kit/blob/main/packages/rpc/src/batchQuery.ts are going to be [unsupported](https://github.com/Agoric/agoric-sdk/tree/master/golang/cosmos/x/vstorage#arbitrary-response-http-interface) in future cosmos sdk versions for paths starting with `/custom/...`. Estimated deadline about 2 months away (mid-december 2023). @JimLarson is driving this.
- Re-assessing importance of 2 TPS limit for dapps. Bandwidth may be more important. Can we do some load testing and see how many open clients one node can handle? Maybe we should try regular RPC requests like casting without proofs.
- Tendermint has a websocket API, but documentation is a bit sparse https://docs.cometbft.com/main/rpc/. Ag-solo uses websockets in some form.
- Disregarding proofs for now.
- Can subscribe to block production events (`tm.event = 'NewBlockHeader'`, and `NewBlock` which has contents) with websockets. Those events will include all vstorage updates per block.
- Example block query https://main.rpc.agoric.net/tx_search?query=%22tm.event=%27NewBlock%27%22&order_by=%22desc%22
- https://www.piesocket.com/websocket-tester?url=wss://agoric.rpc.kjnodes.com:443/websocket
`{ "jsonrpc": "2.0","method": "subscribe","id": 0,"params": {"query": "state_change.store='vstorage'"} }` ([query syntax](https://github.com/cometbft/cometbft/blob/6a3a169bd38402e93c73a7a5120455fa3b7e5d99/libs/pubsub/query/syntax/doc.go))
![image](https://github.com/Agoric/ui-kit/assets/8848650/a42a1920-eab8-4802-8b94-8eef47f260d6)
- Websockets uses a lot of bandwidth, block data is large and can't be filtered down. Tricky to make queries to only get blocks we care about.

**Comment by gibson042** [comment]
> * Dapp batch queries i.e. https://github.com/Agoric/ui-kit/blob/main/packages/rpc/src/batchQuery.ts are going to be [unsupported](https://github.com/Agoric/agoric-sdk/tree/master/golang/cosmos/x/vstorage#arbitrary-response-http-interface) in future cosmos sdk versions for paths starting with `/custom/...`.

FWIW, note that batch queries with `/agoric…` paths will remain supported.
