### ISSUE TITLE
'Unable to connect to chain. Error: no data for vstorage path: not found' error when I launch dapp-inter UI without provisioned wallet

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/ui-kit#58]
## Describe the bug
'Unable to connect to chain. Error: no data for vstorage path: not found' error when I launch dapp-inter UI without provisioned wallet. (Emerynet)

When I provision wallet in Wallet UI and return to dapp - it works.

the vstorage path validation check that 
[@gibson042](https://agoricopco.slack.com/team/U03921SKV60)
 added changed the error message slightly, not knowing this was used in the ui

https://agoricopco.slack.com/archives/C065DVB93NV/p1700076646791179

## To Reproduce
1. Have no wallet provisioned
2. navigate to Emerynet app.inter.trade
3. Get error

## Expected behavior
UI should load, I should get pop-up/ have option to provision wallet from dapp UI

## Screenshots
<img width="436" alt="image" src="https://github.com/Agoric/ui-kit/assets/93355546/d3890844-b0dc-45ab-aaf4-60bf12d601a2">

**Comment by samsiegart** [comment]
This is fixed in dapp-inter main now
