### ISSUE TITLE
Create Provision Smart Wallet Component

### ISSUE THREAD

**Issue by samsiegart** [Agoric/ui-kit#78]
## What is the Problem Being Solved?

A common flow for dapps will be provisioning a smart wallet for users who have not used Agoric dapps before. The two ways to create a smart wallet are:

- Automatically when the user makes their first offer, which deducts 1 IST (subject to chain params) from their account (and gives back 0.25)
- Through a provision message signed by the user, which deducts 10 BLD (subject to chain params) from their account (and gives back 0.25 IST) (See below - no longer a requirement)

Dapp developers should have a way to easily facilitate this flow, perhaps through a dialog that shows the provisioning fee, or react hooks that tell them the provision status of the connected wallet.

Also, a convenient way to use leap elements to let the user acquire the necessary 1 IST would be useful.

**Comment by otoole-brendan** [comment]
Updated Requirements specifying that only auto-provisioning flow payable in IST to be supported/offered and not provisioning signer paying with BLD option.

From [UI Components Requirements doc](https://docs.google.com/document/d/1GGA_CqLhyoisAHCoyGOsFPTtf7hV1EXRgaftvyH889U/edit?usp=sharing):

Requirements
Follows the 1IST auto-provisioning flow already implemented on PSM and Vaults apps. That is - the wallet is auto-provisioned when wallet spend action occurs which deducts 1 IST from user (and deposits 0.25 IST).
Should not include the 10BLD signing transaction flow as an option
Dialog text should be easily customizable by developers
Users should not be able to proceed with the transaction until they have a balance of at least 1IST (to save user from a failing transaction). ‘Proceed’ should illuminate as an option to the user once sufficient IST balance is reached.

**Comment by otoole-brendan** [comment]
@samsiegart This component should include IST balance, and 'Get IST' button to Leap elements modal features a la https://github.com/Agoric/dapp-psm/issues/124
