### ISSUE TITLE
Create example dapp in @agoric/react-components with e2e testing

### ISSUE THREAD

**Issue by samsiegart** [Agoric/ui-kit#86]
## What is the Problem Being Solved?

For testability and local development, it would be beneficial to have an example app in `packages/react-components` that shows how to use the components and provides a basis for e2e testing.

## Description of the Design

Create an example react app in `packages/react-components/src/example` that can be bundled separately from `src/lib`.

TODO integration testing details, pending contract work on dapp-offer-up.

**Comment by LuqiPan** [comment]
Just trying to understand the priority here, would this issue be part of this sprint?

**Comment by LuqiPan** [comment]
Got it. I'll hit you up if I need some code examples then.
